user:
  name:
    maximum: 50
  email:
    maximum: 255
    valid: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
  password:
    minimum: 6
movie:
  home_paginate: 4
  admin_paginate: 16
  is_showing: "is_showing"
date:
  format: "%d-%m-%Y"
datetime:
  format: "%Y-%m-%d %H:%M"
promotion: 1
theater:
  default: 1
